"""add attempt_count to otps

Revision ID: d6fd80cbd2d9
Revises: 163c12599b53
Create Date: 2026-07-08 17:23:37.149814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fd80cbd2d9'
down_revision: Union[str, Sequence[str], None] = '163c12599b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_transactions', 'is_income')
    op.add_column('otps', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'attempt_count')
    op.add_column('budget_transactions', sa.Column('is_income', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
